---
title: "ELISAaPB"
author: "Kathryn Walters"
date: "12/23/2020"
output: html_document
---

```{r setup, include=TRUE, echo=TRUE }

library(drc) # modeling tools
library(tidyverse) # your go to set of functions for messing w/data
library(RColorBrewer) # to make color schemes
#library(ggpubr) # publication quality ggplots ha ha ha
library(ggthemes) # additional themes for ggplot-ing
library(gridExtra) # allows arranging of plots (rows/columns...)
library(splitstackshape)
library(ggpubr)
```

```{r files, include=TRUE, echo=TRUE}
# OD file
OD <- read_csv("20201223_BTG_ELISAall.csv")
colnames(OD) <- c("Sample","Well","OD_450","OD_540","OD_570")

pb <- X20201223_BTG_PBall[,2:4]
colnames(pb)[2] <- c("viability_30min")
colnames(pb)[3] <- c("viability_24")

# join presto blue measurements with ELISA measurements
OD <- left_join(OD, pb, by = "Well")
#OD$FR_24 <- rep(NA,nrow(OD))
```

## ELISA model fit
Fit a 4-parameter model from the standard curve in order to identify the correct paramaters of a formula to convert fluorescence to aldosterone concentrations.

```{r model fit, include=TRUE, echo=FALSE}
# Subtract background signal (measured at 540nm) from target signal (measured at 450nm)
OD$corrected <- OD$OD_450 - OD$OD_540
OD$Sample <- gsub(pattern = "Std", replacement = "std", x = OD$Sample)
OD$Sample <- gsub(pattern = "NSB", replacement = "nsb", x = OD$Sample)
standards <- OD %>% filter(grepl("std", Sample, ignore.case = T)) # one way of creating a new tibble that only contains your standards
nsb <- OD %>% filter(grepl("nsb", Sample)) # one way of creating a new tibble that only contains your NSBs
# create a tibble for the actual concentrations by std name
stdcrvdata <- data.frame(
  Sample=paste0("std",rep(seq(1,7,1),each=2)),
  known=rep(c(4000,1000,250,62.25,15.625,3.906,0),each=2)
  )
# sort standards by name to match the order of 'stdcrvdata' data.
standards <- standards %>% arrange(Sample) %>% dplyr::select(c(Sample,corrected))
# sort stdcrvdata by name to match the order of 'standards' data.
stdcrvdata <- stdcrvdata %>% arrange(Sample)
# check if they are in the same order (I could change this to well location?)
stopifnot(identical(as.factor(standards$Sample), as.factor(stdcrvdata$Sample)))
# combine them together
stdcrvdata <- data.frame(standards,expected=stdcrvdata$known)
colnames(stdcrvdata)[2] <- "measured"
# take out zeros
stdcrvdata <- stdcrvdata %>% filter(expected > 0)
stdcrvdata$logconc <-log10(stdcrvdata$expected)# log10 from conc
# plot(stdcrvdata$logconc, stdcrvdata$measured)
# model the standard curve using generated points.  plot those points in red.
fit <- drm(formula =   measured ~ logconc , data = stdcrvdata, fct = LL.4())
summary(fit)
# This is a description of the variables and terms defined in the 'fit' model.
# x = the independent variable (Absorbance) (Concentration, estimated from the Absorbance)
# y = the dependent variable 
# The 4 estimated parameters consist of the following:
# the minimum value that can be obtained. (this is the ABS at conc. 0)
# a = fit$coefficients[2] 
# d = the maximum value that can be obtained (i.e. what happens at infinite dose)
# c = the point of inflection (i.e. the point on the S shaped curve halfway between a and d)
# b = Hill’s slope of the curve (i.e. this is related to the steepness of the curve at point c).
# Generate points from  model. Pick range from logconc
x <- seq(from = 0, to = 4, length=100)
# from OD ~ d + (a - d)/(1 + (logconc/cc)^b)
y <- (fit$coefficients[2]+ (fit$coefficients[3]- fit$coefficients[2])/(1+(x/fit$coefficients[4])^ fit$coefficients[1])) 
```

## Apply model to calculate aldosterone levels

```{r apply model, echo=FALSE}
# remove standards and NSB wells leaving only experimental measurements
OD <- OD %>% filter(!grepl("std|nsb", Sample))
# here we are applying the equation described above to...
OD$loganswer<- fit$coefficients[4]*( (
    (-1* fit$coefficients[3]+ OD$corrected)/
      (fit$coefficients[2]-OD$corrected))^(1/ fit$coefficients[1])
  )
#used this code below to take care of the funny media only values
# OD$loganswer<- if_else(OD$Sample == 'media', log10(OD$corrected),  fit$coefficients[4]*( (
#     (-1* fit$coefficients[3]+ OD$corrected)/
#       (fit$coefficients[2]-OD$corrected))^(1/ fit$coefficients[1])
#   ))
OD$conc <- 10^OD$loganswer
# write.table(OD,file="20181012_aldosterone_ELISA_batch1_results.csv",sep=";")
OD$below <- OD$conc < min(stdcrvdata$expected)
OD$above <- OD$conc > max(stdcrvdata$expected)
plot(x = stdcrvdata$logconc, y = stdcrvdata$measured, main="log standard curve",
  xlim = c(min(x),max(x)),
  ylim = c(min(y),max(y))
     ) 
lines(x,y, lty="dotted", col="red") 
lines(OD$loganswer, OD$corrected, type="points", col="blue")
```

## Analyze differences in aldosterone concentration and cell viability


```{r aldosterone calculations, echo=FALSE}
#fixing the media only naming pattern
OD$Sample <- gsub(pattern = "mediaOnly", replacement = "media_NA", x = OD$Sample)
#making two columns to describe the treatment vs the stimulation status
OD <- separate(data = OD, col = Sample, into = c("tx","stim"), sep = "_")
#telling it that the stim category should be referenced to the unstimulated category
OD$stim <- relevel(factor(OD$stim), ref = "unstim")
#telling it that the treatment should be referenced to water
OD$tx <- relevel(factor(OD$tx), ref = "water1")
#creating a value bg in which the average of the media columns is taken
bg <- OD %>% filter(tx=="media") %>% summarise(mean(na.omit(conc))) %>% pull()

#creating a concentration column that just subtracts the bg value
OD$conc <- OD$conc - bg
#now getting rid of the media values
OD <- OD %>% filter(tx!="media")

#this used to be fixing a column that had uMRo, might use it to make all the water the same - nm don't do this
#OD$tx <- gsub(x = OD$tx, pattern = "water2", replacement = "water1")
#just telling me what my current categories are
levels(factor(OD$tx))

#OD$tx <- factor(OD$tx, levels = c("DMSO","5","10","20","50","100"))

#OD$Ro_conc <- as.numeric(gsub("DMSO","0", OD$tx))
#OD$batch <- rep("A",nrow(OD))

names(OD)[7] <- "PB_30"
names(OD)[8] <- "PB_24"
write_csv(x = OD, path = "OD_1.csv")
```

```{r aldo pb concentrations}
p_Ro_aldo <- ggline(data = OD, x = "tx",  y = "conc", 
          color = "stim", fill = "stim",
          add = "mean_se",
          position = position_dodge()) +
  theme_few(base_size = 14) +
  labs(title = "",
      subtitle = "",
      y = "Aldosterone pg/mL",
      x = "Treatment") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
p_Ro_aldo

#p_legend <- get_legend(p_Ro_aldo + theme(legend.position="bottom"))
# p_all <- cowplot::plot_grid(
#   p_Ro_aldo + theme(legend.position="none"),
#   p_Ro_PB + theme(legend.position="none"),
#   p_Ro_FR + theme(legend.position="none"),
#   align = 'vh',
#   labels = c("A", "B","C"),
#   hjust = -1,
#   nrow = 1
#   )
# 
# p_all <- cowplot::plot_grid( p_all, p_legend, ncol = 1, rel_heights = c(1, .1))
# 
ggsave(plot = p_Ro_aldo, filename = "plot_ELISAaldoBTGKD.png", width= 12, height = 6)
# ggsave(plot = p_Ro_FR, filename = "./plots/Ro_FR_timepoint12hrs.png", width =12, height = 6)
# ggscatter(data = OD, x = "PB_24", y = "conc", color = "tx", shape = "tx", facet.by = "stim", cor.coef = T, cor.method = "spearman")
# 
# ggscatter(data = OD, x = "FR_24", y = "conc", color = "tx", shape = "tx", facet.by = "stim", cor.coef = T, cor.method = "spearman")
# 
# 
# ggscatter(data = OD, x = "FR_24", y = "PB_24", color = "tx", shape = "tx", facet.by = "stim", cor.coef = T, cor.method = "spearman")
p_Ro_aldo_bar <- ggbarplot(data = OD, x = "tx",  y = "conc", 
          color = "stim", fill = "stim",
          add = "mean_se",
          position = position_dodge(),
          palette = c("black","red")) +
  theme_few(base_size = 14) +
  labs(title = "",
      subtitle = "",
      y = "Aldosterone pg/mL",
      x = "Treatment") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
p_Ro_aldo_bar
# p_Ro_FR_bar <- ggbarplot(data = OD, x = "time",  y = "FR_24", 
#           color = "tx", fill = "tx",
#           add = "mean_se",
#           position = position_dodge()) +
#   theme_few(base_size = 14) +
#   labs(title = "",
#       subtitle = "",
#       y = "FR_360/460",
#       x = "Time, hrs") +
#   theme(axis.text.x = element_text(angle = 60, hjust = 1))
# 
# p_Ro_FR_bar
# ggsave(plot = p_Ro_FR_bar, filename = "./plots/Ro_FR_timepoints12hrsbar.png", width = 12, height = 6)
ggsave(plot = p_Ro_aldo_bar, filename = "plot_ELISAaldoBTGKD_bar.png", width = 12, height = 6)
# 
```

```{r aldo pb conentrations2}

p_Ro_PB30 <- ggbarplot(data = OD, x = "tx",  y = "PB_30", 
          color = "stim", fill = "stim",
          add = "mean_se",
          position = position_dodge(),
          palette = c("black","red")) +
  theme_few(base_size = 14) +
  labs(title = "",
      subtitle = "",
      y = "PB",
      x = "Treatment") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
p_Ro_PB30

p_Ro_PB24 <- ggbarplot(data = OD, x = "tx",  y = "PB_24", 
          color = "stim", fill = "stim",
          add = "mean_se",
          position = position_dodge(),
          palette = c("black","red")) +
  theme_few(base_size = 14) +
  labs(title = "",
      subtitle = "",
      y = "PB",
      x = "Treatment") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
p_Ro_PB24

#p_legend <- get_legend(p_Ro_aldo + theme(legend.position="bottom"))
p_all <- cowplot::plot_grid(
  p_Ro_aldo_bar + theme(legend.position="none"),
  p_Ro_PB30 + theme(legend.position="none"),
  p_Ro_PB24 + theme(legend.position="none"),
  align = 'vh',
  labels = c("A", "B"),
  hjust = -1,
  nrow = 1
  )
p_all
#p_all <- cowplot::plot_grid( p_all, p_legend, ncol = 1, rel_heights = c(1, .1))
p_all
ggsave(plot = p_all, filename = "BTGKD_allplots.png", width = 8, height = 6)
```